name: ausocial
description: A social event app for anna university

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.7
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  google_fonts: ^1.1.0
  flutter_icons: ^1.1.0
  flutter_snake_navigationbar: ^0.4.0+1
  searchable_dropdown: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/homeBG.jpg
    - assets/images/homeBG.png
    - assets/images/googleicon.png
    - assets/images/google_signin.png

  fonts:
    - family: Sriracha
      fonts:
        - asset: assets/fonts/Sriracha-Regular.ttf
    - family: Heaters
      fonts:
        - asset: assets/fonts/Heaters.ttf
